---

- name: This playbook copies a file
  hosts: all
  become: true
  tasks:
   - name: copying a file
     copy:
       src: /home/ansadmin/index.html
       dest: /home/ansadmin
       mode: 0600
       owner: satish
