---

- name: Install httpd
  hosts: all
  become: true

  tasks:
   - name: Install httpd
     yum:
       name: httpd
       state: installed
     notify: start apache

  handlers:
   - name: start apache
     service:
       name: httpd
       state: started
