---

- name: This playbook creates a user
  hosts: ip-172-31-9-122
  become: true
  tasks:
   - name: creating a user
     user:
      name: satishkumar
      
   - name: set password
     user:
       name: satishkumar
       password: "{{ 'satish123' | password_hash('sha512') }}"
